name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Tạo file .env cho các microservice
      - name: Create .env files
        run: |
          echo "MONGODB_AUTH_URI=${{ secrets.MONGODB_AUTH_URI }}" >> auth/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> auth/.env

          echo "MONGODB_PRODUCT_URI=${{ secrets.MONGODB_PRODUCT_URI }}" >> product/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> product/.env
          echo "LOGIN_TEST_USER=${{ secrets.LOGIN_TEST_USER }}" >> product/.env
          echo "LOGIN_TEST_PASSWORD=${{ secrets.LOGIN_TEST_PASSWORD }}" >> product/.env

      # Cài dependency
      - name: Install dependencies
        run: |
          cd auth && npm ci
          cd ../product && npm ci
          cd ..

      # Chạy test cho auth
      - name: Run tests for auth
        run: |
          cd auth
          npm test

      # Chạy test cho product(sau khi auth đã start)
      - name: Run tests for product
        run: |
          cd auth && npm start &
          sleep 5
          cd ../product
          npm test
